services:
  backend:
    build: ./backend
    container_name: paramify-backend
    ports:
      - "3002:3001"
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: paramify-frontend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env.local
    depends_on:
      - backend
    restart: unless-stopped

  deployer:
    image: node:20-bullseye
    container_name: paramify-deployer
    working_dir: /app
    env_file:
      - .env.deployment
    volumes:
      - ./:/app
      - /app/node_modules
    entrypoint: ["bash", "-lc", "chmod +x scripts/deployer-entry.sh; ./scripts/deployer-entry.sh"]
    # Run once and exit
    restart: "no"
